name: Bug Report
description: 报告bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢反馈问题，请填写下方的表单完成本次问题的反馈
  - type: input
    id: log-lottery-version
    attributes:
      label: log-lottery版本
      description: |
        你所使用的 log-lottery  的准确版本。
      placeholder: eg. v0.5.0
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 浏览器及其版本
      description: |
        你是在哪个浏览器中发现的这个问题？最好可以提供浏览器的版本号。
      placeholder: eg. Google Chrome 111.0.5563.110
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 具体问题
      description: |
        出现了什么问题？
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 报错信息
      description: |
        如果有的话，请粘贴你遇到的报错信息或日志。下面输入框中的内容在 issue 提交后会被自动格式化成代码块。
      render: shell
