export { default as AbilitySetting } from './AbilitySetting.vue'
export { default as DataSetting } from './DataSetting.vue'
export { default as LayoutSetting } from './LayoutSetting.vue'
export { default as PatternSetting } from './PatternSetting.vue'
export { default as TextSetting } from './TextSetting.vue'
export { default as ThemeSetting } from './ThemeSetting.vue'
