/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Command: typeof import('./components/ui/command/Command.vue')['default']
    CommandDialog: typeof import('./components/ui/command/CommandDialog.vue')['default']
    CommandEmpty: typeof import('./components/ui/command/CommandEmpty.vue')['default']
    CommandGroup: typeof import('./components/ui/command/CommandGroup.vue')['default']
    CommandInput: typeof import('./components/ui/command/CommandInput.vue')['default']
    CommandItem: typeof import('./components/ui/command/CommandItem.vue')['default']
    CommandList: typeof import('./components/ui/command/CommandList.vue')['default']
    CommandSeparator: typeof import('./components/ui/command/CommandSeparator.vue')['default']
    CommandShortcut: typeof import('./components/ui/command/CommandShortcut.vue')['default']
    DaiysuiTable: typeof import('./components/DaiysuiTable/index.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    EditSeparateDialog: typeof import('./components/NumberSeparate/EditSeparateDialog.vue')['default']
    FileUpload: typeof import('./components/FileUpload/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageSync: typeof import('./components/ImageSync/index.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    PageHeader: typeof import('./components/PageHeader/index.vue')['default']
    Popover: typeof import('./components/ui/popover/Popover.vue')['default']
    PopoverAnchor: typeof import('./components/ui/popover/PopoverAnchor.vue')['default']
    PopoverContent: typeof import('./components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./components/ui/popover/PopoverTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    ToTop: typeof import('./components/ToTop/index.vue')['default']
  }
}
