/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DaiysuiTable: typeof import('./components/DaiysuiTable/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageSync: typeof import('./components/ImageSync/index.vue')['default']
    PlayMusic: typeof import('./components/PlayMusic/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarsBackground: typeof import('./components/StarsBackground/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    Table: typeof import('./components/Table/index.vue')['default']
    ToTop: typeof import('./components/ToTop/index.vue')['default']
  }
}
